# Legacy Replica set
# Can manage pods that were not part of this replica using labels

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    env: demo
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        env: demo
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
          - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      env: demo